//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoWCFClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoDetails", Namespace="http://schemas.datacontract.org/2004/07/AutoWCF")]
    [System.SerializableAttribute()]
    public partial class AutoDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMalliIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HintaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MittarinlukemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Moottorin_tilavuusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolttoaineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rekisteri_pvmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VaritIDField;

        public AutoDetails(decimal hinta, DateTime rekisteri_pvm, decimal moottorin_tilavuus, int mittarinlukema, int autonMerkkiID, int autonMalliID, int varitID, int polttoaineID)
        {
            Hinta = hinta;
            Rekisteri_pvm = rekisteri_pvm;
            Moottorin_tilavuus = moottorin_tilavuus;
            Mittarinlukema = mittarinlukema;
            AutonMerkkiID = autonMerkkiID;
            AutonMalliID = autonMalliID;
            VaritID = varitID;
            PolttoaineID = polttoaineID;
        }

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMalliID {
            get {
                return this.AutonMalliIDField;
            }
            set {
                if ((this.AutonMalliIDField.Equals(value) != true)) {
                    this.AutonMalliIDField = value;
                    this.RaisePropertyChanged("AutonMalliID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID {
            get {
                return this.AutonMerkkiIDField;
            }
            set {
                if ((this.AutonMerkkiIDField.Equals(value) != true)) {
                    this.AutonMerkkiIDField = value;
                    this.RaisePropertyChanged("AutonMerkkiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hinta {
            get {
                return this.HintaField;
            }
            set {
                if ((this.HintaField.Equals(value) != true)) {
                    this.HintaField = value;
                    this.RaisePropertyChanged("Hinta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mittarinlukema {
            get {
                return this.MittarinlukemaField;
            }
            set {
                if ((this.MittarinlukemaField.Equals(value) != true)) {
                    this.MittarinlukemaField = value;
                    this.RaisePropertyChanged("Mittarinlukema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Moottorin_tilavuus {
            get {
                return this.Moottorin_tilavuusField;
            }
            set {
                if ((this.Moottorin_tilavuusField.Equals(value) != true)) {
                    this.Moottorin_tilavuusField = value;
                    this.RaisePropertyChanged("Moottorin_tilavuus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolttoaineID {
            get {
                return this.PolttoaineIDField;
            }
            set {
                if ((this.PolttoaineIDField.Equals(value) != true)) {
                    this.PolttoaineIDField = value;
                    this.RaisePropertyChanged("PolttoaineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rekisteri_pvm {
            get {
                return this.Rekisteri_pvmField;
            }
            set {
                if ((this.Rekisteri_pvmField.Equals(value) != true)) {
                    this.Rekisteri_pvmField = value;
                    this.RaisePropertyChanged("Rekisteri_pvm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VaritID {
            get {
                return this.VaritIDField;
            }
            set {
                if ((this.VaritIDField.Equals(value) != true)) {
                    this.VaritIDField = value;
                    this.RaisePropertyChanged("VaritID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerkkiDetails", Namespace="http://schemas.datacontract.org/2004/07/AutoWCF")]
    [System.SerializableAttribute()]
    public partial class MerkkiDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerkkiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Merkki {
            get {
                return this.MerkkiField;
            }
            set {
                if ((object.ReferenceEquals(this.MerkkiField, value) != true)) {
                    this.MerkkiField = value;
                    this.RaisePropertyChanged("Merkki");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalliDetails", Namespace="http://schemas.datacontract.org/2004/07/AutoWCF")]
    [System.SerializableAttribute()]
    public partial class MalliDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auton_mallin_nimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID {
            get {
                return this.AutonMerkkiIDField;
            }
            set {
                if ((this.AutonMerkkiIDField.Equals(value) != true)) {
                    this.AutonMerkkiIDField = value;
                    this.RaisePropertyChanged("AutonMerkkiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auton_mallin_nimi {
            get {
                return this.Auton_mallin_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Auton_mallin_nimiField, value) != true)) {
                    this.Auton_mallin_nimiField = value;
                    this.RaisePropertyChanged("Auton_mallin_nimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolttoaineDetails", Namespace="http://schemas.datacontract.org/2004/07/AutoWCF")]
    [System.SerializableAttribute()]
    public partial class PolttoaineDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Polttoaineen_nimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polttoaineen_nimi {
            get {
                return this.Polttoaineen_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Polttoaineen_nimiField, value) != true)) {
                    this.Polttoaineen_nimiField = value;
                    this.RaisePropertyChanged("Polttoaineen_nimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VariDetails", Namespace="http://schemas.datacontract.org/2004/07/AutoWCF")]
    [System.SerializableAttribute()]
    public partial class VariDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Varin_nimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varin_nimi {
            get {
                return this.Varin_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Varin_nimiField, value) != true)) {
                    this.Varin_nimiField = value;
                    this.RaisePropertyChanged("Varin_nimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAutoDetails", ReplyAction="http://tempuri.org/IService1/InsertAutoDetailsResponse")]
        string InsertAutoDetails(AutoWCFClient.ServiceReference1.AutoDetails autoInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAutoDetails", ReplyAction="http://tempuri.org/IService1/InsertAutoDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertAutoDetailsAsync(AutoWCFClient.ServiceReference1.AutoDetails autoInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDatabase", ReplyAction="http://tempuri.org/IService1/ConnectDatabaseResponse")]
        bool ConnectDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConnectDatabase", ReplyAction="http://tempuri.org/IService1/ConnectDatabaseResponse")]
        System.Threading.Tasks.Task<bool> ConnectDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisconnectDatabase", ReplyAction="http://tempuri.org/IService1/DisconnectDatabaseResponse")]
        void DisconnectDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisconnectDatabase", ReplyAction="http://tempuri.org/IService1/DisconnectDatabaseResponse")]
        System.Threading.Tasks.Task DisconnectDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChooseAutoMax", ReplyAction="http://tempuri.org/IService1/ChooseAutoMaxResponse")]
        AutoWCFClient.ServiceReference1.AutoDetails ChooseAutoMax();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChooseAutoMax", ReplyAction="http://tempuri.org/IService1/ChooseAutoMaxResponse")]
        System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> ChooseAutoMaxAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChooseAutoMin", ReplyAction="http://tempuri.org/IService1/ChooseAutoMinResponse")]
        AutoWCFClient.ServiceReference1.AutoDetails ChooseAutoMin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChooseAutoMin", ReplyAction="http://tempuri.org/IService1/ChooseAutoMinResponse")]
        System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> ChooseAutoMinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectNextAutoRow", ReplyAction="http://tempuri.org/IService1/SelectNextAutoRowResponse")]
        AutoWCFClient.ServiceReference1.AutoDetails SelectNextAutoRow(int selectedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectNextAutoRow", ReplyAction="http://tempuri.org/IService1/SelectNextAutoRowResponse")]
        System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> SelectNextAutoRowAsync(int selectedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPreviousAutoRow", ReplyAction="http://tempuri.org/IService1/SelectPreviousAutoRowResponse")]
        AutoWCFClient.ServiceReference1.AutoDetails SelectPreviousAutoRow(int selectedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPreviousAutoRow", ReplyAction="http://tempuri.org/IService1/SelectPreviousAutoRowResponse")]
        System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> SelectPreviousAutoRowAsync(int selectedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAutoMakersFromDatabase", ReplyAction="http://tempuri.org/IService1/GetAllAutoMakersFromDatabaseResponse")]
        System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MerkkiDetails> GetAllAutoMakersFromDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllAutoMakersFromDatabase", ReplyAction="http://tempuri.org/IService1/GetAllAutoMakersFromDatabaseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MerkkiDetails>> GetAllAutoMakersFromDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAutoModelsByMakerId", ReplyAction="http://tempuri.org/IService1/GetAutoModelsByMakerIdResponse")]
        System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MalliDetails> GetAutoModelsByMakerId(int makerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAutoModelsByMakerId", ReplyAction="http://tempuri.org/IService1/GetAutoModelsByMakerIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MalliDetails>> GetAutoModelsByMakerIdAsync(int makerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFuelsFromDatabase", ReplyAction="http://tempuri.org/IService1/GetAllFuelsFromDatabaseResponse")]
        System.Collections.Generic.List<AutoWCFClient.ServiceReference1.PolttoaineDetails> GetAllFuelsFromDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFuelsFromDatabase", ReplyAction="http://tempuri.org/IService1/GetAllFuelsFromDatabaseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.PolttoaineDetails>> GetAllFuelsFromDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetColorsFromDatabase", ReplyAction="http://tempuri.org/IService1/GetColorsFromDatabaseResponse")]
        System.Collections.Generic.List<AutoWCFClient.ServiceReference1.VariDetails> GetColorsFromDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetColorsFromDatabase", ReplyAction="http://tempuri.org/IService1/GetColorsFromDatabaseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.VariDetails>> GetColorsFromDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRowFromDatabase", ReplyAction="http://tempuri.org/IService1/DeleteRowFromDatabaseResponse")]
        int DeleteRowFromDatabase(int selectedID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRowFromDatabase", ReplyAction="http://tempuri.org/IService1/DeleteRowFromDatabaseResponse")]
        System.Threading.Tasks.Task<int> DeleteRowFromDatabaseAsync(int selectedID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AutoWCFClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AutoWCFClient.ServiceReference1.IService1>, AutoWCFClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertAutoDetails(AutoWCFClient.ServiceReference1.AutoDetails autoInfo) {
            return base.Channel.InsertAutoDetails(autoInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertAutoDetailsAsync(AutoWCFClient.ServiceReference1.AutoDetails autoInfo) {
            return base.Channel.InsertAutoDetailsAsync(autoInfo);
        }
        
        public bool ConnectDatabase() {
            return base.Channel.ConnectDatabase();
        }
        
        public System.Threading.Tasks.Task<bool> ConnectDatabaseAsync() {
            return base.Channel.ConnectDatabaseAsync();
        }
        
        public void DisconnectDatabase() {
            base.Channel.DisconnectDatabase();
        }
        
        public System.Threading.Tasks.Task DisconnectDatabaseAsync() {
            return base.Channel.DisconnectDatabaseAsync();
        }
        
        public AutoWCFClient.ServiceReference1.AutoDetails ChooseAutoMax() {
            return base.Channel.ChooseAutoMax();
        }
        
        public System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> ChooseAutoMaxAsync() {
            return base.Channel.ChooseAutoMaxAsync();
        }
        
        public AutoWCFClient.ServiceReference1.AutoDetails ChooseAutoMin() {
            return base.Channel.ChooseAutoMin();
        }
        
        public System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> ChooseAutoMinAsync() {
            return base.Channel.ChooseAutoMinAsync();
        }
        
        public AutoWCFClient.ServiceReference1.AutoDetails SelectNextAutoRow(int selectedID) {
            return base.Channel.SelectNextAutoRow(selectedID);
        }
        
        public System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> SelectNextAutoRowAsync(int selectedID) {
            return base.Channel.SelectNextAutoRowAsync(selectedID);
        }
        
        public AutoWCFClient.ServiceReference1.AutoDetails SelectPreviousAutoRow(int selectedID) {
            return base.Channel.SelectPreviousAutoRow(selectedID);
        }
        
        public System.Threading.Tasks.Task<AutoWCFClient.ServiceReference1.AutoDetails> SelectPreviousAutoRowAsync(int selectedID) {
            return base.Channel.SelectPreviousAutoRowAsync(selectedID);
        }
        
        public System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MerkkiDetails> GetAllAutoMakersFromDatabase() {
            return base.Channel.GetAllAutoMakersFromDatabase();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MerkkiDetails>> GetAllAutoMakersFromDatabaseAsync() {
            return base.Channel.GetAllAutoMakersFromDatabaseAsync();
        }
        
        public System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MalliDetails> GetAutoModelsByMakerId(int makerId) {
            return base.Channel.GetAutoModelsByMakerId(makerId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.MalliDetails>> GetAutoModelsByMakerIdAsync(int makerId) {
            return base.Channel.GetAutoModelsByMakerIdAsync(makerId);
        }
        
        public System.Collections.Generic.List<AutoWCFClient.ServiceReference1.PolttoaineDetails> GetAllFuelsFromDatabase() {
            return base.Channel.GetAllFuelsFromDatabase();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.PolttoaineDetails>> GetAllFuelsFromDatabaseAsync() {
            return base.Channel.GetAllFuelsFromDatabaseAsync();
        }
        
        public System.Collections.Generic.List<AutoWCFClient.ServiceReference1.VariDetails> GetColorsFromDatabase() {
            return base.Channel.GetColorsFromDatabase();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AutoWCFClient.ServiceReference1.VariDetails>> GetColorsFromDatabaseAsync() {
            return base.Channel.GetColorsFromDatabaseAsync();
        }
        
        public int DeleteRowFromDatabase(int selectedID) {
            return base.Channel.DeleteRowFromDatabase(selectedID);
        }
        
        public System.Threading.Tasks.Task<int> DeleteRowFromDatabaseAsync(int selectedID) {
            return base.Channel.DeleteRowFromDatabaseAsync(selectedID);
        }
    }
}
